spring:
  application:
    name: activityservice
  mongodb:
    uri: mongodb://localhost:27017/activityfitness
    database: activityfitness


eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/


server:
  port: 8082

rabbitmq:
  exchange:
    name: activity.exchange
  routing:
    key: activity.routing.key

userservice:
  url: http://localhost:8081
