spring:
    application:
        name: aiservice
    mongodb:
        uri: mongodb://localhost:27017/airecommendationfitness
        database: airecommendationfitness


eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/


server:
  port: 8083

rabbitmq:
  queue:
    name: activity.queue
  exchange:
    name: activity.exchange
  routing:
    key: activity.routing.key