spring:
    mongodb:
        uri: mongodb://localhost:27017/airecommendationfitness
        database: airecommendationfitness


eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/


server:
  port: 8083

rabbitmq:
  queue:
    name: activity.queue
  exchange:
    name: activity.exchange
  routing:
    key: activity.routing.key

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
    key: ${GEMINI_API_KEY:}