spring.application.name=userservice

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_micro-user
spring.datasource.username=postgres
spring.datasource.password=dhruvyadav123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true